#CyberShield Database Configuration
#db.mode: 'auto' (try MySQL, fallback to embedded), 'mysql' (force MySQL), 'embedded' (force H2 embedded)
#Thu Oct 08 13:43:23 IST 2026
db.mode=auto
embedded.path=./data/cybershield
mysql.database=cybershield_db
mysql.host=localhost
mysql.password=
mysql.port=3306
mysql.user=root
